name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run unit tests
        run: npm test

  archives:
    name: Check downloading archives
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
      - name: List files
        run: find $OPENVINO_INSTALL_DIR
        shell: bash
      - name: Check installation
        run: integration-tests/check-installation.sh
        shell: bash
        if: ${{ startsWith(runner.os, 'linux') }}

  old:
    name: Spot-check old archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
        with:
          version: 2022.2
          release: rhel8
          env: false
      - name: List files
        run: find $OPENVINO_INSTALL_DIR
      - name: Check installation
        run: integration-tests/check-installation.sh
        shell: bash

  apt:
    name: Check installing APT packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
        with:
          apt: true
          # TODO: the latest release (v2023.0.0) is not yet available as an APT package; update this
          # when it is.
          version: 2022.3.0
      - name: List files
        run: |
          apt-cache depends openvino-2022.3.0 --installed
          dpkg --listfiles libopenvino-2022.3.0
        shell: bash
      - name: Check installation
        run: ldconfig -p | grep openvino

  env:
    name: Check environment changes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Capture initial environment
        run: env > before.env
        shell: bash
        if: ${{ !startsWith(runner.os, 'windows') }}
      - name: Capture initial environment
        run: set > before.env
        shell: cmd
        if: ${{ startsWith(runner.os, 'windows') }}
      - name: Install OpenVINO
        uses: ./
      - name: Capture environment again
        run: env > after.env
        shell: bash
        if: ${{ !startsWith(runner.os, 'windows') }}
      - name: Capture environment again
        run: set > after.env
        shell: cmd
        if: ${{ startsWith(runner.os, 'windows') }}
      - name: Compare "before" and "after" environments
        run: git diff --no-index before.env after.env || echo "differences found"
        shell: bash

