name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    name: Check action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
      - name: Check installation
        run: source /opt/intel/openvino_2022/setupvars.sh
