name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run unit tests
        run: npm test

  archives:
    name: Check downloading archives
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
      - name: List files
        run: find $OPENVINO_INSTALL_DIR
        shell: bash
      - name: Check installation
        run: integration-tests/check-installation.sh
        shell: bash
        if: ${{ startsWith(runner.os, 'linux') }}

  old:
    name: Spot-check old archives
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Check that the RHEL archives also work (more out of curiosity than anything else).
          - version: 2022.2
            release: rhel8
          # Check that older versions, not present for Ubuntu 22.04, downgrade to the Ubuntu 20.04
          # versions.
          - version: 2022.3
            release: ubuntu22
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
        with:
          version: ${{ matrix.version }}
          release: ${{ matrix.release }}
          # We do not use the setup script to prepare the environment due to a conflicting Python
          # version with the GitHub runner.
          env: false
      # While the action attempts to install needed prerequisites (i.e., TBB), when we start using
      # non-GitHub-runner versions we may need to tweak this a bit:
      - name: Install extra version of TBB
        run: sudo apt-get install -y libtbb2
      - name: List files
        run: find $OPENVINO_INSTALL_DIR
      - name: Check installation
        run: integration-tests/check-installation.sh
        shell: bash

  apt:
    name: Check installing APT packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVINO
        uses: ./
        with:
          apt: true
      - name: List files
        run: |
          apt-cache depends openvino-2024.4.0 --installed
          dpkg --listfiles libopenvino-2024.4.0
        shell: bash
      - name: Check installation
        run: ldconfig -p | grep openvino
